Add containerization for the ipa-tuura+Apache service
freeipa/ipa-tuura pull request #47
Opened 2023-06-06 12:28 UTC by antoniotorresm

Add Containerfile and podman-compose files that containerize ipa-tuura using httpd as HTTPS server. This replaces the previous Dockerfile.test, using Apache HTTPS server instead of the insecure built-in Django HTTP server.

By running the podman-compose.yaml, the container is built and deployed with the needed port mapping.

2023-06-06 13:42 UTC, antoniotorresm commented on Containerfile
> +FROM fedora:38
Thanks, updated.

2023-06-06 14:32 UTC, Tiboris commented
Weird, the automation does not pick the PR

2023-06-06 16:12 UTC, f-trivino commented on .github/workflows/gating.yaml
> +            ./Containerfile
I think we should keep using a Development mode container for gating workflow. Maybe we should improve the naming?

2023-06-06 16:14 UTC, f-trivino commented on Dockerfile.test
> -FROM fedora:38
I wouldn't delete this file, perhaps improve some aspects:

2023-06-06 16:14 UTC, f-trivino commented on Dockerfile.test
> -FROM fedora:38
FROM registry.fedoraproject.org/fedora:38

2023-06-06 16:14 UTC, f-trivino commented on Dockerfile.test
> -RUN pip install dbus-python python-ldap
these two should go to requirements.txt

2023-06-06 16:15 UTC, f-trivino commented on Dockerfile.test
> -RUN python3 src/ipa-tuura/manage.py test
this code line is important for gating, this is how we run the unit tests

2023-06-06 16:16 UTC, f-trivino commented on podman-compose.yaml
> +version: "3"
this file can be just an example on how to deploy in production mode, I think we should set ENVVARS in addition, check: 

https://github.com/freeipa/ipa-tuura/pull/43

2023-06-06 16:17 UTC, f-trivino commented on src/conf/ipa.conf
> +DNS.1 = *.ipa.test
we need to think how to handle these hard-coded values.

2023-06-06 16:17 UTC, f-trivino commented on src/conf/ipa.conf
> +# Key:
perhaps we could delete all comments and keep just the settigns.

2023-06-06 16:21 UTC, f-trivino requested changes
thanks for the PR @antoniotorresm , I added few comments. I would also improve the commit message and include the issue ticket:

Related: https://github.com/freeipa/ipa-tuura/issues/29

I'm not sure if we are ready to switch everything to prod. This PR could be just the configuration files so that it is simple to deploy in prod until we figure out how to test this mode.

2023-06-07 12:58 UTC, Tiboris commented
I think gating should use production Dockerfile whatever that means in `gating.yaml` definition we can later just exec the `python3 src/ipa-tuura/manage.py test` as a step after the container will be built. Or if we want to have both Dockerfiles or as you like Containerfiles we should share as many layers as possible from each other.

2023-06-13 14:15 UTC, f-trivino commented on src/prod/Containerfile
> +RUN sed -i 's/staticfiles/static/g' /usr/local/lib/python3.11/site-packages/rest_framework_swagger/templates/rest_framework_swagger/index.html
since swagger is not usable through HTTPs I think we can remove this line45.

2023-06-13 14:18 UTC, f-trivino commented on src/prod/conf/ipa.conf
> +DNS.4 = master.ipa.test
I know that we will improve this when enabling extra automation such as certbot, but let's change "master.ipa.test" by "bridge.ipa.test". Service is supposed to be deployed in a separate domain as ipa domain.

2023-06-13 14:18 UTC, f-trivino commented on src/prod/podman-compose.yaml
> +      - DJANGO_DEBUG='True'
DJANGO_DEBUG='False' is intended for production.

2023-06-13 14:19 UTC, f-trivino reviewed
@antoniotorresm added few comments.

2023-06-13 15:01 UTC, antoniotorresm commented
Thanks, pushed requested changes.

2023-06-13 15:04 UTC, f-trivino approved these changes
LGTM.

2023-06-13 15:04 UTC, merged