Add endpoint for GSSAPI Authentication
freeipa/ipa-tuura pull request #88
Opened 2024-01-09 09:52 UTC by antoniotorresm

Add the `login_kerberos` endpoint for handling GSSAPI authentications. mod_auth_gssapi and gssproxy are included as dependencies. Additional steps are included to the IPA domain addition, such as the addition of the HTTP service and keytab retrieval. Additionally, `login_password` endpoint is provided as well, which requests a ticket using the user and password passed with the client request.

2024-01-12 13:12 UTC, abbra commented on src/ipa-tuura/domains/utils.py
> +    http_principal = "HTTP/%s@%s" % (hostname, realm)
Here is the problem. We should not use bridge's hostname here. Instead our keytab should contain a key which will correspond to the keycloak's host. I think you should make a separate confgiuration entry for this.

The idea is that this whole setup will be:

client browser -> Keycloak service -> IPA bridge

and GSSAPI authentication would happen between the client browser and Keycloak service. From that service a headers for that exchange would be forwarded to the bridge and then to the login end-point we have created. Here they'll be processed.

From GSSAPI point of view the client would ask for a service ticket to the Keycloak service host. It would be `HTTP/keycloak-hostname`, not `HTTP/ipatuura-hostname`. Since we'd have the keytab for `HTTP/keycloak-hostname` service key, we will be able to decode it.

2024-01-23 09:38 UTC, antoniotorresm commented on src/ipa-tuura/domains/utils.py
> +    http_principal = "HTTP/%s@%s" % (hostname, realm)
What do you think about receiving the keycloak hostname as part of the request and using that for creating the `HTTP/keycloak-hostname` service and requesting the keytab during domain creation? I have already added the automation for `setspn.exe`, if we have the keycloak hostname we could automate keytab retrieval as well.

2024-01-24 14:27 UTC, antoniotorresm commented
Added a new field to the domain model, `keycloak_hostname` that will take the hostname for the Keycloak host. I have also added automation for SPN creation and keytab retrieval on AD hosts.

2024-02-09 12:40 UTC, antoniotorresm commented
/ok-to-test

2024-02-09 12:41 UTC, antoniotorresm commented
/retest

2024-02-15 11:03 UTC, f-trivino approved these changes
LGTM!
I have tested the new end-points for IPA and AD use cases using the same curl calls:

`curl -k -v -X POST --negotiate -u : https://bridge.ipa.test/bridge/login_kerberos/`

` curl -k -v -X POST https://bridge.ipa.test/bridge/login_password/ --data 'user=ipauser&password=Secret123'`

I think the PR covers the initial feature for IPA and AD, and it can be easily extended later on to cover RHDS/LDAPwithKerberos. 

Ref testing, we are enabling RedHatTrustedPipeline and the plan is to run extensive e2e tests there.

2024-02-15 11:23 UTC, abbra requested changes
I added few in-line comments.

2024-02-15 11:23 UTC, abbra commented on src/ipa-tuura/domains/utils.py
> +
For this whole block of `ipa-getkeytab` use -- check that `http_principal` is different from `http_bridge_principal` and only then run the second one. Otherwise you are invalidating the first one.

2024-02-15 11:23 UTC, abbra commented on src/ipa-tuura/domains/utils.py
> +        f"ktpass -out /httpd.keytab -mapUser ipatuura@{ad_realm} -pass {ad_passwd} -mapOp set +DumpSalt -crypto AES256-SHA1 -ptype KRB5_NT_PRINCIPAL -princ HTTP/{kc_hostname}@{ad_realm} -kvno $kvno;"
You might want to allow encryption type list be configurable. There are plenty of environments where people are still using RC4 (sorry) or AES128-SHA1. Also, with Windows Server 2025 there will be support for RFC8009 encrytpion types (SHA2-based) so it is best to remove the hard-coded encryption lines here and instead add a configuration with sensible defaults.

2024-02-15 11:23 UTC, abbra commented on src/ipa-tuura/domains/utils.py
> +            f"Administrator@{ad_server}:C:/httpd.keytab",
Same here with `Administrator` -- the account used for AD (and IPA admin, for that reason) must be configurable.

2024-02-15 13:22 UTC, antoniotorresm commented on src/ipa-tuura/domains/utils.py
> +        f"ktpass -out /httpd.keytab -mapUser ipatuura@{ad_realm} -pass {ad_passwd} -mapOp set +DumpSalt -crypto AES256-SHA1 -ptype KRB5_NT_PRINCIPAL -princ HTTP/{kc_hostname}@{ad_realm} -kvno $kvno;"
Created ticket #100 to address this.

2024-02-16 14:51 UTC, antoniotorresm commented
Added `Remote-User` response header, needed for Keycloak plugin.

2024-02-20 12:15 UTC, merged